name: Deploy Frontend Infrastructure

on:
  push:
    branches: ["main"]
    paths:
      - "terraform/**"
      - ".github/workflows/deploy-infra.yml"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Authenticate to GCP via WIF
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Debug Active Identity & Bucket Access
        run: |
          echo "================ ACTIVE IDENTITY ================"
          gcloud config get-value account
          echo "================ TEST BUCKET ACCESS ============="
          gcloud storage ls gs://${{ secrets.GCP_PROJECT_ID }}-tfstate

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "latest"

      - name: Terraform Init
        run: |
          cd terraform
          terraform init -backend-config="bucket=${{ secrets.GCP_PROJECT_ID }}-tfstate"

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}" -var="github_repository=${{ github.repository }}"
