name: Deploy Frontend Application

on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "public/**"
      - "index.html"
      - "package*.json"
      - "tsconfig*.json"
      - "vite.config.*"
      - "Dockerfile"
      - "nginx.conf"
      - "k8s/**"
      - ".github/workflows/deploy-app.yml"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  GAR_LOCATION: australia-southeast1
  REPOSITORY: todo-frontend-repo
  IMAGE_NAME: todo-frontend
  CLUSTER_NAME: todo-cluster

jobs:
  build-scan-deploy:
    name: Build, Scan & Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Authenticate to GCP via WIF
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v3"

      - name: Configure Docker CLI for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build Docker Image Locally
        uses: docker/build-push-action@v7
        with:
          context: .
          load: true
          tags: |
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
